// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-server/internal/biz"
	"kratos-server/internal/conf"
	"kratos-server/internal/data"
	"kratos-server/internal/server"
	"kratos-server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := newServerConf(bootstrap)
	confData := newDataConf(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, bootstrap, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, bootstrap, logger)
	ruleChainRepo := data.NewRuleChainRepo(dataData, logger)
	ruleGoService, err := service.NewRuleGoService(bootstrap, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	bizRuleGoService := service.NewRuleGoAdapter(ruleGoService)
	ruleChainUsecase := biz.NewRuleChainUsecase(ruleChainRepo, bizRuleGoService, logger)
	ruleService := service.NewRuleService(ruleChainUsecase, logger)
	componentRepo := data.NewComponentRepo(dataData, logger)
	componentUsecase := biz.NewComponentUsecase(componentRepo, logger)
	componentService := service.NewComponentService(componentUsecase, logger)
	runLogRepo := data.NewRunLogRepo(dataData, logger)
	runLogUsecase := biz.NewRunLogUsecase(runLogRepo, logger)
	logService := service.NewLogService(runLogUsecase, logger)
	localeService := service.NewLocaleService(logger)
	grpcServer := server.NewGRPCServer(confServer, userService, ruleService, componentService, logService, localeService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, ruleService, componentService, logService, localeService, logger)
	app := newApp(logger, grpcServer, httpServer, ruleGoService)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// 提供器函数用于从 Bootstrap 中提取配置
func newServerConf(bc *conf.Bootstrap) *conf.Server {
	return bc.Server
}

func newDataConf(bc *conf.Bootstrap) *conf.Data {
	return bc.Data
}
