version: "3"
services:
  # editor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.editor
  #   container_name: editor
  #   ports:
  #     - "9997:80"
  #   restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "9998:80"
    restart: always
  workflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workflow
    ports:
      - "9099:9091"
    volumes:
      - ./volumes/rulego_data:/app/data
      - ./volumes/rulego_logs:/app/logs
    environment:
      - RULEGO_SERVER=:9091
      - RULEGO_MCP_LOAD_COMPONENTS_AS_TOOL=false
      - RULEGO_DEBUG=true
      - RULEGO_LOG_FILE=./logs/rulego.log
      - RULEGO_SAVE_RUN_LOG=true
    restart: always
networks:
  rulego:
    ipam:
      config:
        - subnet: 192.100.0.0/16
