version: "3"
services:
  workflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workflow
    ports:
      - "9099:9091"
    volumes:
      - ./volumes/rulego_data:/app/data
      - ./volumes/rulego_logs:/app/logs
    environment:
      - RULEGO_SERVER=:9091
      - RULEGO_MCP_LOAD_COMPONENTS_AS_TOOL=true
      - RULEGO_DEBUG=true
      - RULEGO_LOG_FILE=./logs/rulego.log
      - RULEGO_SAVE_RUN_LOG=true
      - RULEGO_RESOURCE_MAPPING=/editor/=/app/editor,/images/=/app/editor/images
      - RULEGO_POSTGRE_USER=rulego
      - RULEGO_POSTGRE_PASSWORD=rulego
      - RULEGO_POSTGRE_HOST=postgres-db
      - RULEGO_POSTGRE_PORT=5432
      - RULEGO_POSTGRE_DBNAME=rulego
    restart: always
  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rulego
      POSTGRES_PASSWORD: rulego
    volumes:
      - ./volumes/database_postgres-data:/var/lib/postgresql/data
networks:
  rulego:
    ipam:
      config:
        - subnet: 192.100.0.0/16
