// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: rulego/v1/component.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComponentServiceClient is the client API for ComponentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComponentServiceClient interface {
	// 获取所有组件列表
	ListComponents(ctx context.Context, in *ListComponentsRequest, opts ...grpc.CallOption) (*ListComponentsResponse, error)
	// 获取自定义动态组件列表
	ListCustomComponents(ctx context.Context, in *ListCustomComponentsRequest, opts ...grpc.CallOption) (*ListCustomComponentsResponse, error)
	// 获取自定义动态组件DSL
	GetCustomComponentDSL(ctx context.Context, in *GetCustomComponentDSLRequest, opts ...grpc.CallOption) (*GetCustomComponentDSLResponse, error)
	// 安装/升级自定义动态组件
	UpgradeCustomComponent(ctx context.Context, in *UpgradeCustomComponentRequest, opts ...grpc.CallOption) (*UpgradeCustomComponentResponse, error)
	// 卸载自定义动态组件
	UninstallCustomComponent(ctx context.Context, in *UninstallCustomComponentRequest, opts ...grpc.CallOption) (*UninstallCustomComponentResponse, error)
	// 获取所有共享组件
	ListSharedComponents(ctx context.Context, in *ListSharedComponentsRequest, opts ...grpc.CallOption) (*ListSharedComponentsResponse, error)
	// 获取组件市场组件列表
	ListMarketplaceComponents(ctx context.Context, in *ListMarketplaceComponentsRequest, opts ...grpc.CallOption) (*ListMarketplaceComponentsResponse, error)
}

type componentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComponentServiceClient(cc grpc.ClientConnInterface) ComponentServiceClient {
	return &componentServiceClient{cc}
}

func (c *componentServiceClient) ListComponents(ctx context.Context, in *ListComponentsRequest, opts ...grpc.CallOption) (*ListComponentsResponse, error) {
	out := new(ListComponentsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/ListComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) ListCustomComponents(ctx context.Context, in *ListCustomComponentsRequest, opts ...grpc.CallOption) (*ListCustomComponentsResponse, error) {
	out := new(ListCustomComponentsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/ListCustomComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) GetCustomComponentDSL(ctx context.Context, in *GetCustomComponentDSLRequest, opts ...grpc.CallOption) (*GetCustomComponentDSLResponse, error) {
	out := new(GetCustomComponentDSLResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/GetCustomComponentDSL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) UpgradeCustomComponent(ctx context.Context, in *UpgradeCustomComponentRequest, opts ...grpc.CallOption) (*UpgradeCustomComponentResponse, error) {
	out := new(UpgradeCustomComponentResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/UpgradeCustomComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) UninstallCustomComponent(ctx context.Context, in *UninstallCustomComponentRequest, opts ...grpc.CallOption) (*UninstallCustomComponentResponse, error) {
	out := new(UninstallCustomComponentResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/UninstallCustomComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) ListSharedComponents(ctx context.Context, in *ListSharedComponentsRequest, opts ...grpc.CallOption) (*ListSharedComponentsResponse, error) {
	out := new(ListSharedComponentsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/ListSharedComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *componentServiceClient) ListMarketplaceComponents(ctx context.Context, in *ListMarketplaceComponentsRequest, opts ...grpc.CallOption) (*ListMarketplaceComponentsResponse, error) {
	out := new(ListMarketplaceComponentsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.ComponentService/ListMarketplaceComponents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComponentServiceServer is the server API for ComponentService service.
// All implementations must embed UnimplementedComponentServiceServer
// for forward compatibility
type ComponentServiceServer interface {
	// 获取所有组件列表
	ListComponents(context.Context, *ListComponentsRequest) (*ListComponentsResponse, error)
	// 获取自定义动态组件列表
	ListCustomComponents(context.Context, *ListCustomComponentsRequest) (*ListCustomComponentsResponse, error)
	// 获取自定义动态组件DSL
	GetCustomComponentDSL(context.Context, *GetCustomComponentDSLRequest) (*GetCustomComponentDSLResponse, error)
	// 安装/升级自定义动态组件
	UpgradeCustomComponent(context.Context, *UpgradeCustomComponentRequest) (*UpgradeCustomComponentResponse, error)
	// 卸载自定义动态组件
	UninstallCustomComponent(context.Context, *UninstallCustomComponentRequest) (*UninstallCustomComponentResponse, error)
	// 获取所有共享组件
	ListSharedComponents(context.Context, *ListSharedComponentsRequest) (*ListSharedComponentsResponse, error)
	// 获取组件市场组件列表
	ListMarketplaceComponents(context.Context, *ListMarketplaceComponentsRequest) (*ListMarketplaceComponentsResponse, error)
	mustEmbedUnimplementedComponentServiceServer()
}

// UnimplementedComponentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComponentServiceServer struct {
}

func (UnimplementedComponentServiceServer) ListComponents(context.Context, *ListComponentsRequest) (*ListComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComponents not implemented")
}
func (UnimplementedComponentServiceServer) ListCustomComponents(context.Context, *ListCustomComponentsRequest) (*ListCustomComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCustomComponents not implemented")
}
func (UnimplementedComponentServiceServer) GetCustomComponentDSL(context.Context, *GetCustomComponentDSLRequest) (*GetCustomComponentDSLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomComponentDSL not implemented")
}
func (UnimplementedComponentServiceServer) UpgradeCustomComponent(context.Context, *UpgradeCustomComponentRequest) (*UpgradeCustomComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeCustomComponent not implemented")
}
func (UnimplementedComponentServiceServer) UninstallCustomComponent(context.Context, *UninstallCustomComponentRequest) (*UninstallCustomComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UninstallCustomComponent not implemented")
}
func (UnimplementedComponentServiceServer) ListSharedComponents(context.Context, *ListSharedComponentsRequest) (*ListSharedComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSharedComponents not implemented")
}
func (UnimplementedComponentServiceServer) ListMarketplaceComponents(context.Context, *ListMarketplaceComponentsRequest) (*ListMarketplaceComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMarketplaceComponents not implemented")
}
func (UnimplementedComponentServiceServer) mustEmbedUnimplementedComponentServiceServer() {}

// UnsafeComponentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComponentServiceServer will
// result in compilation errors.
type UnsafeComponentServiceServer interface {
	mustEmbedUnimplementedComponentServiceServer()
}

func RegisterComponentServiceServer(s grpc.ServiceRegistrar, srv ComponentServiceServer) {
	s.RegisterService(&ComponentService_ServiceDesc, srv)
}

func _ComponentService_ListComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).ListComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/ListComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).ListComponents(ctx, req.(*ListComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_ListCustomComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).ListCustomComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/ListCustomComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).ListCustomComponents(ctx, req.(*ListCustomComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_GetCustomComponentDSL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomComponentDSLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).GetCustomComponentDSL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/GetCustomComponentDSL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).GetCustomComponentDSL(ctx, req.(*GetCustomComponentDSLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_UpgradeCustomComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeCustomComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).UpgradeCustomComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/UpgradeCustomComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).UpgradeCustomComponent(ctx, req.(*UpgradeCustomComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_UninstallCustomComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallCustomComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).UninstallCustomComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/UninstallCustomComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).UninstallCustomComponent(ctx, req.(*UninstallCustomComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_ListSharedComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).ListSharedComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/ListSharedComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).ListSharedComponents(ctx, req.(*ListSharedComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComponentService_ListMarketplaceComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketplaceComponentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComponentServiceServer).ListMarketplaceComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.ComponentService/ListMarketplaceComponents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComponentServiceServer).ListMarketplaceComponents(ctx, req.(*ListMarketplaceComponentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComponentService_ServiceDesc is the grpc.ServiceDesc for ComponentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComponentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rulego.v1.ComponentService",
	HandlerType: (*ComponentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComponents",
			Handler:    _ComponentService_ListComponents_Handler,
		},
		{
			MethodName: "ListCustomComponents",
			Handler:    _ComponentService_ListCustomComponents_Handler,
		},
		{
			MethodName: "GetCustomComponentDSL",
			Handler:    _ComponentService_GetCustomComponentDSL_Handler,
		},
		{
			MethodName: "UpgradeCustomComponent",
			Handler:    _ComponentService_UpgradeCustomComponent_Handler,
		},
		{
			MethodName: "UninstallCustomComponent",
			Handler:    _ComponentService_UninstallCustomComponent_Handler,
		},
		{
			MethodName: "ListSharedComponents",
			Handler:    _ComponentService_ListSharedComponents_Handler,
		},
		{
			MethodName: "ListMarketplaceComponents",
			Handler:    _ComponentService_ListMarketplaceComponents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rulego/v1/component.proto",
}
