// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: rulego/v1/log.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// 获取调试日志
	GetDebugLogs(ctx context.Context, in *GetDebugLogsRequest, opts ...grpc.CallOption) (*GetDebugLogsResponse, error)
	// 获取运行日志列表
	ListRunLogs(ctx context.Context, in *ListRunLogsRequest, opts ...grpc.CallOption) (*ListRunLogsResponse, error)
	// 删除运行日志
	DeleteRunLogs(ctx context.Context, in *DeleteRunLogsRequest, opts ...grpc.CallOption) (*DeleteRunLogsResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) GetDebugLogs(ctx context.Context, in *GetDebugLogsRequest, opts ...grpc.CallOption) (*GetDebugLogsResponse, error) {
	out := new(GetDebugLogsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.LogService/GetDebugLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ListRunLogs(ctx context.Context, in *ListRunLogsRequest, opts ...grpc.CallOption) (*ListRunLogsResponse, error) {
	out := new(ListRunLogsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.LogService/ListRunLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) DeleteRunLogs(ctx context.Context, in *DeleteRunLogsRequest, opts ...grpc.CallOption) (*DeleteRunLogsResponse, error) {
	out := new(DeleteRunLogsResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.LogService/DeleteRunLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility
type LogServiceServer interface {
	// 获取调试日志
	GetDebugLogs(context.Context, *GetDebugLogsRequest) (*GetDebugLogsResponse, error)
	// 获取运行日志列表
	ListRunLogs(context.Context, *ListRunLogsRequest) (*ListRunLogsResponse, error)
	// 删除运行日志
	DeleteRunLogs(context.Context, *DeleteRunLogsRequest) (*DeleteRunLogsResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (UnimplementedLogServiceServer) GetDebugLogs(context.Context, *GetDebugLogsRequest) (*GetDebugLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDebugLogs not implemented")
}
func (UnimplementedLogServiceServer) ListRunLogs(context.Context, *ListRunLogsRequest) (*ListRunLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunLogs not implemented")
}
func (UnimplementedLogServiceServer) DeleteRunLogs(context.Context, *DeleteRunLogsRequest) (*DeleteRunLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRunLogs not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_GetDebugLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDebugLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetDebugLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.LogService/GetDebugLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetDebugLogs(ctx, req.(*GetDebugLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ListRunLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ListRunLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.LogService/ListRunLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ListRunLogs(ctx, req.(*ListRunLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_DeleteRunLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DeleteRunLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.LogService/DeleteRunLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DeleteRunLogs(ctx, req.(*DeleteRunLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rulego.v1.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDebugLogs",
			Handler:    _LogService_GetDebugLogs_Handler,
		},
		{
			MethodName: "ListRunLogs",
			Handler:    _LogService_ListRunLogs_Handler,
		},
		{
			MethodName: "DeleteRunLogs",
			Handler:    _LogService_DeleteRunLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rulego/v1/log.proto",
}

// LocaleServiceClient is the client API for LocaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocaleServiceClient interface {
	// 获取本地化配置
	GetLocales(ctx context.Context, in *GetLocalesRequest, opts ...grpc.CallOption) (*GetLocalesResponse, error)
	// 保存本地化配置
	SaveLocales(ctx context.Context, in *SaveLocalesRequest, opts ...grpc.CallOption) (*SaveLocalesResponse, error)
}

type localeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocaleServiceClient(cc grpc.ClientConnInterface) LocaleServiceClient {
	return &localeServiceClient{cc}
}

func (c *localeServiceClient) GetLocales(ctx context.Context, in *GetLocalesRequest, opts ...grpc.CallOption) (*GetLocalesResponse, error) {
	out := new(GetLocalesResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.LocaleService/GetLocales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localeServiceClient) SaveLocales(ctx context.Context, in *SaveLocalesRequest, opts ...grpc.CallOption) (*SaveLocalesResponse, error) {
	out := new(SaveLocalesResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.LocaleService/SaveLocales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocaleServiceServer is the server API for LocaleService service.
// All implementations must embed UnimplementedLocaleServiceServer
// for forward compatibility
type LocaleServiceServer interface {
	// 获取本地化配置
	GetLocales(context.Context, *GetLocalesRequest) (*GetLocalesResponse, error)
	// 保存本地化配置
	SaveLocales(context.Context, *SaveLocalesRequest) (*SaveLocalesResponse, error)
	mustEmbedUnimplementedLocaleServiceServer()
}

// UnimplementedLocaleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLocaleServiceServer struct {
}

func (UnimplementedLocaleServiceServer) GetLocales(context.Context, *GetLocalesRequest) (*GetLocalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocales not implemented")
}
func (UnimplementedLocaleServiceServer) SaveLocales(context.Context, *SaveLocalesRequest) (*SaveLocalesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLocales not implemented")
}
func (UnimplementedLocaleServiceServer) mustEmbedUnimplementedLocaleServiceServer() {}

// UnsafeLocaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocaleServiceServer will
// result in compilation errors.
type UnsafeLocaleServiceServer interface {
	mustEmbedUnimplementedLocaleServiceServer()
}

func RegisterLocaleServiceServer(s grpc.ServiceRegistrar, srv LocaleServiceServer) {
	s.RegisterService(&LocaleService_ServiceDesc, srv)
}

func _LocaleService_GetLocales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocaleServiceServer).GetLocales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.LocaleService/GetLocales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocaleServiceServer).GetLocales(ctx, req.(*GetLocalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocaleService_SaveLocales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLocalesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocaleServiceServer).SaveLocales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.LocaleService/SaveLocales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocaleServiceServer).SaveLocales(ctx, req.(*SaveLocalesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocaleService_ServiceDesc is the grpc.ServiceDesc for LocaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rulego.v1.LocaleService",
	HandlerType: (*LocaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocales",
			Handler:    _LocaleService_GetLocales_Handler,
		},
		{
			MethodName: "SaveLocales",
			Handler:    _LocaleService_SaveLocales_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rulego/v1/log.proto",
}
