// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: rulego/v1/rule.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRuleServiceCreateComponentUseRule = "/api.rulego.v1.RuleService/CreateComponentUseRule"
const OperationRuleServiceDeleteComponentUseRule = "/api.rulego.v1.RuleService/DeleteComponentUseRule"
const OperationRuleServiceDeleteRule = "/api.rulego.v1.RuleService/DeleteRule"
const OperationRuleServiceExecuteRule = "/api.rulego.v1.RuleService/ExecuteRule"
const OperationRuleServiceGetComponentUseRule = "/api.rulego.v1.RuleService/GetComponentUseRule"
const OperationRuleServiceGetLatestRule = "/api.rulego.v1.RuleService/GetLatestRule"
const OperationRuleServiceGetRule = "/api.rulego.v1.RuleService/GetRule"
const OperationRuleServiceListComponentUseRules = "/api.rulego.v1.RuleService/ListComponentUseRules"
const OperationRuleServiceListRules = "/api.rulego.v1.RuleService/ListRules"
const OperationRuleServiceOperateRule = "/api.rulego.v1.RuleService/OperateRule"
const OperationRuleServicePostMessage = "/api.rulego.v1.RuleService/PostMessage"
const OperationRuleServiceSaveRule = "/api.rulego.v1.RuleService/SaveRule"
const OperationRuleServiceSaveRuleBaseInfo = "/api.rulego.v1.RuleService/SaveRuleBaseInfo"
const OperationRuleServiceSaveRuleConfiguration = "/api.rulego.v1.RuleService/SaveRuleConfiguration"
const OperationRuleServiceUpdateComponentUseRule = "/api.rulego.v1.RuleService/UpdateComponentUseRule"

type RuleServiceHTTPServer interface {
	CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleResponse, error)
	DeleteComponentUseRule(context.Context, *DeleteComponentUseRuleRequest) (*DeleteComponentUseRuleResponse, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	ExecuteRule(context.Context, *ExecuteRuleRequest) (*ExecuteRuleResponse, error)
	GetComponentUseRule(context.Context, *GetComponentUseRuleRequest) (*GetComponentUseRuleResponse, error)
	GetLatestRule(context.Context, *GetLatestRuleRequest) (*GetLatestRuleResponse, error)
	GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	ListComponentUseRules(context.Context, *ListComponentUseRulesRequest) (*ListComponentUseRulesResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	OperateRule(context.Context, *OperateRuleRequest) (*OperateRuleResponse, error)
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	SaveRule(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error)
	SaveRuleBaseInfo(context.Context, *SaveRuleBaseInfoRequest) (*SaveRuleBaseInfoResponse, error)
	SaveRuleConfiguration(context.Context, *SaveRuleConfigurationRequest) (*SaveRuleConfigurationResponse, error)
	UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleResponse, error)
}

func RegisterRuleServiceHTTPServer(s *http.Server, srv RuleServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/rules", _RuleService_ListRules0_HTTP_Handler(srv))
	r.GET("/api/v1/rules/{id}", _RuleService_GetRule0_HTTP_Handler(srv))
	r.GET("/api/v1/rules/{id}/latest", _RuleService_GetLatestRule0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}", _RuleService_SaveRule0_HTTP_Handler(srv))
	r.DELETE("/api/v1/rules/{id}", _RuleService_DeleteRule0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}/base", _RuleService_SaveRuleBaseInfo0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}/config/{var_type}", _RuleService_SaveRuleConfiguration0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}/execute/{msg_type}", _RuleService_ExecuteRule0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}/notify/{msg_type}", _RuleService_PostMessage0_HTTP_Handler(srv))
	r.POST("/api/v1/rules/{id}/operate/{type}", _RuleService_OperateRule0_HTTP_Handler(srv))
	r.POST("/api/v1/componentUseRule/create", _RuleService_CreateComponentUseRule0_HTTP_Handler(srv))
	r.GET("/api/v1/componentUseRule/get", _RuleService_GetComponentUseRule0_HTTP_Handler(srv))
	r.DELETE("/api/v1/componentUseRule/delete", _RuleService_DeleteComponentUseRule0_HTTP_Handler(srv))
	r.POST("/api/v1/componentUseRule/update", _RuleService_UpdateComponentUseRule0_HTTP_Handler(srv))
	r.GET("/api/v1/componentUseRule/page", _RuleService_ListComponentUseRules0_HTTP_Handler(srv))
}

func _RuleService_ListRules0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRulesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceListRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRules(ctx, req.(*ListRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRulesResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_GetRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceGetRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRule(ctx, req.(*GetRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_GetLatestRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLatestRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceGetLatestRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLatestRule(ctx, req.(*GetLatestRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLatestRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_SaveRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceSaveRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveRule(ctx, req.(*SaveRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_DeleteRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceDeleteRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRule(ctx, req.(*DeleteRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_SaveRuleBaseInfo0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveRuleBaseInfoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceSaveRuleBaseInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveRuleBaseInfo(ctx, req.(*SaveRuleBaseInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveRuleBaseInfoResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_SaveRuleConfiguration0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveRuleConfigurationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceSaveRuleConfiguration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveRuleConfiguration(ctx, req.(*SaveRuleConfigurationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveRuleConfigurationResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_ExecuteRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceExecuteRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteRule(ctx, req.(*ExecuteRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_PostMessage0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PostMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServicePostMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PostMessage(ctx, req.(*PostMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PostMessageResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_OperateRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OperateRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceOperateRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OperateRule(ctx, req.(*OperateRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_CreateComponentUseRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateComponentUseRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceCreateComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateComponentUseRule(ctx, req.(*CreateComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateComponentUseRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_GetComponentUseRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetComponentUseRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceGetComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetComponentUseRule(ctx, req.(*GetComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetComponentUseRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_DeleteComponentUseRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteComponentUseRuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceDeleteComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteComponentUseRule(ctx, req.(*DeleteComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteComponentUseRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_UpdateComponentUseRule0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateComponentUseRuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceUpdateComponentUseRule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateComponentUseRule(ctx, req.(*UpdateComponentUseRuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateComponentUseRuleResponse)
		return ctx.Result(200, reply)
	}
}

func _RuleService_ListComponentUseRules0_HTTP_Handler(srv RuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListComponentUseRulesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRuleServiceListComponentUseRules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListComponentUseRules(ctx, req.(*ListComponentUseRulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListComponentUseRulesResponse)
		return ctx.Result(200, reply)
	}
}

type RuleServiceHTTPClient interface {
	CreateComponentUseRule(ctx context.Context, req *CreateComponentUseRuleRequest, opts ...http.CallOption) (rsp *CreateComponentUseRuleResponse, err error)
	DeleteComponentUseRule(ctx context.Context, req *DeleteComponentUseRuleRequest, opts ...http.CallOption) (rsp *DeleteComponentUseRuleResponse, err error)
	DeleteRule(ctx context.Context, req *DeleteRuleRequest, opts ...http.CallOption) (rsp *DeleteRuleResponse, err error)
	ExecuteRule(ctx context.Context, req *ExecuteRuleRequest, opts ...http.CallOption) (rsp *ExecuteRuleResponse, err error)
	GetComponentUseRule(ctx context.Context, req *GetComponentUseRuleRequest, opts ...http.CallOption) (rsp *GetComponentUseRuleResponse, err error)
	GetLatestRule(ctx context.Context, req *GetLatestRuleRequest, opts ...http.CallOption) (rsp *GetLatestRuleResponse, err error)
	GetRule(ctx context.Context, req *GetRuleRequest, opts ...http.CallOption) (rsp *GetRuleResponse, err error)
	ListComponentUseRules(ctx context.Context, req *ListComponentUseRulesRequest, opts ...http.CallOption) (rsp *ListComponentUseRulesResponse, err error)
	ListRules(ctx context.Context, req *ListRulesRequest, opts ...http.CallOption) (rsp *ListRulesResponse, err error)
	OperateRule(ctx context.Context, req *OperateRuleRequest, opts ...http.CallOption) (rsp *OperateRuleResponse, err error)
	PostMessage(ctx context.Context, req *PostMessageRequest, opts ...http.CallOption) (rsp *PostMessageResponse, err error)
	SaveRule(ctx context.Context, req *SaveRuleRequest, opts ...http.CallOption) (rsp *SaveRuleResponse, err error)
	SaveRuleBaseInfo(ctx context.Context, req *SaveRuleBaseInfoRequest, opts ...http.CallOption) (rsp *SaveRuleBaseInfoResponse, err error)
	SaveRuleConfiguration(ctx context.Context, req *SaveRuleConfigurationRequest, opts ...http.CallOption) (rsp *SaveRuleConfigurationResponse, err error)
	UpdateComponentUseRule(ctx context.Context, req *UpdateComponentUseRuleRequest, opts ...http.CallOption) (rsp *UpdateComponentUseRuleResponse, err error)
}

type RuleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRuleServiceHTTPClient(client *http.Client) RuleServiceHTTPClient {
	return &RuleServiceHTTPClientImpl{client}
}

func (c *RuleServiceHTTPClientImpl) CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...http.CallOption) (*CreateComponentUseRuleResponse, error) {
	var out CreateComponentUseRuleResponse
	pattern := "/api/v1/componentUseRule/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceCreateComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) DeleteComponentUseRule(ctx context.Context, in *DeleteComponentUseRuleRequest, opts ...http.CallOption) (*DeleteComponentUseRuleResponse, error) {
	var out DeleteComponentUseRuleResponse
	pattern := "/api/v1/componentUseRule/delete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceDeleteComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...http.CallOption) (*DeleteRuleResponse, error) {
	var out DeleteRuleResponse
	pattern := "/api/v1/rules/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceDeleteRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) ExecuteRule(ctx context.Context, in *ExecuteRuleRequest, opts ...http.CallOption) (*ExecuteRuleResponse, error) {
	var out ExecuteRuleResponse
	pattern := "/api/v1/rules/{id}/execute/{msg_type}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceExecuteRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) GetComponentUseRule(ctx context.Context, in *GetComponentUseRuleRequest, opts ...http.CallOption) (*GetComponentUseRuleResponse, error) {
	var out GetComponentUseRuleResponse
	pattern := "/api/v1/componentUseRule/get"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceGetComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) GetLatestRule(ctx context.Context, in *GetLatestRuleRequest, opts ...http.CallOption) (*GetLatestRuleResponse, error) {
	var out GetLatestRuleResponse
	pattern := "/api/v1/rules/{id}/latest"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceGetLatestRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) GetRule(ctx context.Context, in *GetRuleRequest, opts ...http.CallOption) (*GetRuleResponse, error) {
	var out GetRuleResponse
	pattern := "/api/v1/rules/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceGetRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) ListComponentUseRules(ctx context.Context, in *ListComponentUseRulesRequest, opts ...http.CallOption) (*ListComponentUseRulesResponse, error) {
	var out ListComponentUseRulesResponse
	pattern := "/api/v1/componentUseRule/page"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceListComponentUseRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) ListRules(ctx context.Context, in *ListRulesRequest, opts ...http.CallOption) (*ListRulesResponse, error) {
	var out ListRulesResponse
	pattern := "/api/v1/rules"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRuleServiceListRules))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) OperateRule(ctx context.Context, in *OperateRuleRequest, opts ...http.CallOption) (*OperateRuleResponse, error) {
	var out OperateRuleResponse
	pattern := "/api/v1/rules/{id}/operate/{type}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceOperateRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...http.CallOption) (*PostMessageResponse, error) {
	var out PostMessageResponse
	pattern := "/api/v1/rules/{id}/notify/{msg_type}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServicePostMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) SaveRule(ctx context.Context, in *SaveRuleRequest, opts ...http.CallOption) (*SaveRuleResponse, error) {
	var out SaveRuleResponse
	pattern := "/api/v1/rules/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceSaveRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) SaveRuleBaseInfo(ctx context.Context, in *SaveRuleBaseInfoRequest, opts ...http.CallOption) (*SaveRuleBaseInfoResponse, error) {
	var out SaveRuleBaseInfoResponse
	pattern := "/api/v1/rules/{id}/base"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceSaveRuleBaseInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) SaveRuleConfiguration(ctx context.Context, in *SaveRuleConfigurationRequest, opts ...http.CallOption) (*SaveRuleConfigurationResponse, error) {
	var out SaveRuleConfigurationResponse
	pattern := "/api/v1/rules/{id}/config/{var_type}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceSaveRuleConfiguration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RuleServiceHTTPClientImpl) UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...http.CallOption) (*UpdateComponentUseRuleResponse, error) {
	var out UpdateComponentUseRuleResponse
	pattern := "/api/v1/componentUseRule/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRuleServiceUpdateComponentUseRule))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
