// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: rulego/v1/rule.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RuleServiceClient is the client API for RuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleServiceClient interface {
	// 获取规则链列表
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	// 获取规则链详情
	GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error)
	// 获取最新的规则链
	GetLatestRule(ctx context.Context, in *GetLatestRuleRequest, opts ...grpc.CallOption) (*GetLatestRuleResponse, error)
	// 保存规则链
	SaveRule(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error)
	// 删除规则链
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
	// 保存规则链基本信息
	SaveRuleBaseInfo(ctx context.Context, in *SaveRuleBaseInfoRequest, opts ...grpc.CallOption) (*SaveRuleBaseInfoResponse, error)
	// 保存规则链配置
	SaveRuleConfiguration(ctx context.Context, in *SaveRuleConfigurationRequest, opts ...grpc.CallOption) (*SaveRuleConfigurationResponse, error)
	// 执行规则链
	ExecuteRule(ctx context.Context, in *ExecuteRuleRequest, opts ...grpc.CallOption) (*ExecuteRuleResponse, error)
	// 推送消息到规则链
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error)
	// 操作规则链（部署/下线）
	OperateRule(ctx context.Context, in *OperateRuleRequest, opts ...grpc.CallOption) (*OperateRuleResponse, error)
	// 组件使用规则相关接口
	CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...grpc.CallOption) (*CreateComponentUseRuleResponse, error)
	GetComponentUseRule(ctx context.Context, in *GetComponentUseRuleRequest, opts ...grpc.CallOption) (*GetComponentUseRuleResponse, error)
	DeleteComponentUseRule(ctx context.Context, in *DeleteComponentUseRuleRequest, opts ...grpc.CallOption) (*DeleteComponentUseRuleResponse, error)
	UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...grpc.CallOption) (*UpdateComponentUseRuleResponse, error)
	ListComponentUseRules(ctx context.Context, in *ListComponentUseRulesRequest, opts ...grpc.CallOption) (*ListComponentUseRulesResponse, error)
}

type ruleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleServiceClient(cc grpc.ClientConnInterface) RuleServiceClient {
	return &ruleServiceClient{cc}
}

func (c *ruleServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/ListRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*GetRuleResponse, error) {
	out := new(GetRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/GetRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetLatestRule(ctx context.Context, in *GetLatestRuleRequest, opts ...grpc.CallOption) (*GetLatestRuleResponse, error) {
	out := new(GetLatestRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/GetLatestRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) SaveRule(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error) {
	out := new(SaveRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/SaveRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/DeleteRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) SaveRuleBaseInfo(ctx context.Context, in *SaveRuleBaseInfoRequest, opts ...grpc.CallOption) (*SaveRuleBaseInfoResponse, error) {
	out := new(SaveRuleBaseInfoResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/SaveRuleBaseInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) SaveRuleConfiguration(ctx context.Context, in *SaveRuleConfigurationRequest, opts ...grpc.CallOption) (*SaveRuleConfigurationResponse, error) {
	out := new(SaveRuleConfigurationResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/SaveRuleConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ExecuteRule(ctx context.Context, in *ExecuteRuleRequest, opts ...grpc.CallOption) (*ExecuteRuleResponse, error) {
	out := new(ExecuteRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/ExecuteRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/PostMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) OperateRule(ctx context.Context, in *OperateRuleRequest, opts ...grpc.CallOption) (*OperateRuleResponse, error) {
	out := new(OperateRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/OperateRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) CreateComponentUseRule(ctx context.Context, in *CreateComponentUseRuleRequest, opts ...grpc.CallOption) (*CreateComponentUseRuleResponse, error) {
	out := new(CreateComponentUseRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/CreateComponentUseRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetComponentUseRule(ctx context.Context, in *GetComponentUseRuleRequest, opts ...grpc.CallOption) (*GetComponentUseRuleResponse, error) {
	out := new(GetComponentUseRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/GetComponentUseRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) DeleteComponentUseRule(ctx context.Context, in *DeleteComponentUseRuleRequest, opts ...grpc.CallOption) (*DeleteComponentUseRuleResponse, error) {
	out := new(DeleteComponentUseRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/DeleteComponentUseRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) UpdateComponentUseRule(ctx context.Context, in *UpdateComponentUseRuleRequest, opts ...grpc.CallOption) (*UpdateComponentUseRuleResponse, error) {
	out := new(UpdateComponentUseRuleResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/UpdateComponentUseRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) ListComponentUseRules(ctx context.Context, in *ListComponentUseRulesRequest, opts ...grpc.CallOption) (*ListComponentUseRulesResponse, error) {
	out := new(ListComponentUseRulesResponse)
	err := c.cc.Invoke(ctx, "/api.rulego.v1.RuleService/ListComponentUseRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServiceServer is the server API for RuleService service.
// All implementations must embed UnimplementedRuleServiceServer
// for forward compatibility
type RuleServiceServer interface {
	// 获取规则链列表
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	// 获取规则链详情
	GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error)
	// 获取最新的规则链
	GetLatestRule(context.Context, *GetLatestRuleRequest) (*GetLatestRuleResponse, error)
	// 保存规则链
	SaveRule(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error)
	// 删除规则链
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	// 保存规则链基本信息
	SaveRuleBaseInfo(context.Context, *SaveRuleBaseInfoRequest) (*SaveRuleBaseInfoResponse, error)
	// 保存规则链配置
	SaveRuleConfiguration(context.Context, *SaveRuleConfigurationRequest) (*SaveRuleConfigurationResponse, error)
	// 执行规则链
	ExecuteRule(context.Context, *ExecuteRuleRequest) (*ExecuteRuleResponse, error)
	// 推送消息到规则链
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	// 操作规则链（部署/下线）
	OperateRule(context.Context, *OperateRuleRequest) (*OperateRuleResponse, error)
	// 组件使用规则相关接口
	CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleResponse, error)
	GetComponentUseRule(context.Context, *GetComponentUseRuleRequest) (*GetComponentUseRuleResponse, error)
	DeleteComponentUseRule(context.Context, *DeleteComponentUseRuleRequest) (*DeleteComponentUseRuleResponse, error)
	UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleResponse, error)
	ListComponentUseRules(context.Context, *ListComponentUseRulesRequest) (*ListComponentUseRulesResponse, error)
	mustEmbedUnimplementedRuleServiceServer()
}

// UnimplementedRuleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRuleServiceServer struct {
}

func (UnimplementedRuleServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedRuleServiceServer) GetRule(context.Context, *GetRuleRequest) (*GetRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedRuleServiceServer) GetLatestRule(context.Context, *GetLatestRuleRequest) (*GetLatestRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRule not implemented")
}
func (UnimplementedRuleServiceServer) SaveRule(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRule not implemented")
}
func (UnimplementedRuleServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedRuleServiceServer) SaveRuleBaseInfo(context.Context, *SaveRuleBaseInfoRequest) (*SaveRuleBaseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRuleBaseInfo not implemented")
}
func (UnimplementedRuleServiceServer) SaveRuleConfiguration(context.Context, *SaveRuleConfigurationRequest) (*SaveRuleConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRuleConfiguration not implemented")
}
func (UnimplementedRuleServiceServer) ExecuteRule(context.Context, *ExecuteRuleRequest) (*ExecuteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteRule not implemented")
}
func (UnimplementedRuleServiceServer) PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedRuleServiceServer) OperateRule(context.Context, *OperateRuleRequest) (*OperateRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperateRule not implemented")
}
func (UnimplementedRuleServiceServer) CreateComponentUseRule(context.Context, *CreateComponentUseRuleRequest) (*CreateComponentUseRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComponentUseRule not implemented")
}
func (UnimplementedRuleServiceServer) GetComponentUseRule(context.Context, *GetComponentUseRuleRequest) (*GetComponentUseRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponentUseRule not implemented")
}
func (UnimplementedRuleServiceServer) DeleteComponentUseRule(context.Context, *DeleteComponentUseRuleRequest) (*DeleteComponentUseRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComponentUseRule not implemented")
}
func (UnimplementedRuleServiceServer) UpdateComponentUseRule(context.Context, *UpdateComponentUseRuleRequest) (*UpdateComponentUseRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComponentUseRule not implemented")
}
func (UnimplementedRuleServiceServer) ListComponentUseRules(context.Context, *ListComponentUseRulesRequest) (*ListComponentUseRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComponentUseRules not implemented")
}
func (UnimplementedRuleServiceServer) mustEmbedUnimplementedRuleServiceServer() {}

// UnsafeRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleServiceServer will
// result in compilation errors.
type UnsafeRuleServiceServer interface {
	mustEmbedUnimplementedRuleServiceServer()
}

func RegisterRuleServiceServer(s grpc.ServiceRegistrar, srv RuleServiceServer) {
	s.RegisterService(&RuleService_ServiceDesc, srv)
}

func _RuleService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/ListRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/GetRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetRule(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetLatestRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetLatestRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/GetLatestRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetLatestRule(ctx, req.(*GetLatestRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_SaveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).SaveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/SaveRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).SaveRule(ctx, req.(*SaveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/DeleteRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_SaveRuleBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRuleBaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).SaveRuleBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/SaveRuleBaseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).SaveRuleBaseInfo(ctx, req.(*SaveRuleBaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_SaveRuleConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRuleConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).SaveRuleConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/SaveRuleConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).SaveRuleConfiguration(ctx, req.(*SaveRuleConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ExecuteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ExecuteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/ExecuteRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ExecuteRule(ctx, req.(*ExecuteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/PostMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_OperateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).OperateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/OperateRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).OperateRule(ctx, req.(*OperateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_CreateComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).CreateComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/CreateComponentUseRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).CreateComponentUseRule(ctx, req.(*CreateComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/GetComponentUseRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetComponentUseRule(ctx, req.(*GetComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_DeleteComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).DeleteComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/DeleteComponentUseRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).DeleteComponentUseRule(ctx, req.(*DeleteComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_UpdateComponentUseRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComponentUseRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).UpdateComponentUseRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/UpdateComponentUseRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).UpdateComponentUseRule(ctx, req.(*UpdateComponentUseRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_ListComponentUseRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListComponentUseRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).ListComponentUseRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.rulego.v1.RuleService/ListComponentUseRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).ListComponentUseRules(ctx, req.(*ListComponentUseRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleService_ServiceDesc is the grpc.ServiceDesc for RuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rulego.v1.RuleService",
	HandlerType: (*RuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRules",
			Handler:    _RuleService_ListRules_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _RuleService_GetRule_Handler,
		},
		{
			MethodName: "GetLatestRule",
			Handler:    _RuleService_GetLatestRule_Handler,
		},
		{
			MethodName: "SaveRule",
			Handler:    _RuleService_SaveRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _RuleService_DeleteRule_Handler,
		},
		{
			MethodName: "SaveRuleBaseInfo",
			Handler:    _RuleService_SaveRuleBaseInfo_Handler,
		},
		{
			MethodName: "SaveRuleConfiguration",
			Handler:    _RuleService_SaveRuleConfiguration_Handler,
		},
		{
			MethodName: "ExecuteRule",
			Handler:    _RuleService_ExecuteRule_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _RuleService_PostMessage_Handler,
		},
		{
			MethodName: "OperateRule",
			Handler:    _RuleService_OperateRule_Handler,
		},
		{
			MethodName: "CreateComponentUseRule",
			Handler:    _RuleService_CreateComponentUseRule_Handler,
		},
		{
			MethodName: "GetComponentUseRule",
			Handler:    _RuleService_GetComponentUseRule_Handler,
		},
		{
			MethodName: "DeleteComponentUseRule",
			Handler:    _RuleService_DeleteComponentUseRule_Handler,
		},
		{
			MethodName: "UpdateComponentUseRule",
			Handler:    _RuleService_UpdateComponentUseRule_Handler,
		},
		{
			MethodName: "ListComponentUseRules",
			Handler:    _RuleService_ListComponentUseRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rulego/v1/rule.proto",
}
